export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const GET_SYSTEM_REQUEST = "GET_SYSTEM_REQUEST";
export const GET_SYSTEM_SUCCESS = "GET_SYSTEM_SUCCESS";
export const GET_SYSTEM_ERROR = "GET_SYSTEM_ERROR";

export const GET_DARKMODE = "GET_DARKMODE";

export const SET_FILTER_VALUE_SOURCE_CODE = "SET_FILTER_VALUE_SOURCE_CODE";

// BALANCE
export const SET_DISPLAY_BALANCE = "SET_DISPLAY_BALANCE";
export const SET_BALANCE = "SET_BALANCE";
export const UPDATE_BALANCE = "UPDATE_BALANCE";

// GAME KENO 1P
export const SET_TIMER_KENO_1P = "SET_TIMER_KENO_1P";
export const SET_PHIEN_KENO_1P = "SET_PHIEN_KENO_1P";
export const SET_TINH_TRANG_KENO_1P = "SET_TINH_TRANG_KENO_1P";
export const SET_KET_QUA_PHIEN_TRUOC_KENO_1P = "SET_KET_QUA_PHIEN_TRUOC_KENO_1P";
export const SET_KET_QUA_KENO_1P = "SET_KET_QUA_KENO_1P";
export const SET_IS_PLAY_GAME_KENO_1P = "SET_IS_PLAY_GAME_KENO_1P";
// GAME KENO 3P
export const SET_TIMER_KENO_3P = "SET_TIMER_KENO_3P";
export const SET_PHIEN_KENO_3P = "SET_PHIEN_KENO_3P";
export const SET_TINH_TRANG_KENO_3P = "SET_TINH_TRANG_KENO_3P";
export const SET_KET_QUA_PHIEN_TRUOC_KENO_3P = "SET_KET_QUA_PHIEN_TRUOC_KENO_3P";
export const SET_KET_QUA_KENO_3P = "SET_KET_QUA_KENO_3P";
export const SET_IS_PLAY_GAME_KENO_3P = "SET_IS_PLAY_GAME_KENO_3P";

// GAME KENO 5P
export const SET_TIMER_KENO_5P = "SET_TIMER_KENO_5P";
export const SET_PHIEN_KENO_5P = "SET_PHIEN_KENO_5P";
export const SET_TINH_TRANG_KENO_5P = "SET_TINH_TRANG_KENO_5P";
export const SET_KET_QUA_PHIEN_TRUOC_KENO_5P = "SET_KET_QUA_PHIEN_TRUOC_KENO_5P";
export const SET_KET_QUA_KENO_5P = "SET_KET_QUA_KENO_5P";
export const SET_IS_PLAY_GAME_KENO_5P = "SET_IS_PLAY_GAME_KENO_5P";

// GAME XUCXAC 1P
export const SET_TIMER_XUCXAC_1P = "SET_TIMER_XUCXAC_1P";
export const SET_PHIEN_XUCXAC_1P = "SET_PHIEN_XUCXAC_1P";
export const SET_TINH_TRANG_XUCXAC_1P = "SET_TINH_TRANG_XUCXAC_1P";
export const SET_KET_QUA_PHIEN_TRUOC_XUCXAC_1P = "SET_KET_QUA_PHIEN_TRUOC_XUCXAC_1P";
export const SET_KET_QUA_XUCXAC_1P = "SET_KET_QUA_XUCXAC_1P";
export const SET_IS_PLAY_GAME_XUCXAC_1P = "SET_IS_PLAY_GAME_XUCXAC_1P";

// GAME XUCXAC 3P
export const SET_TIMER_XUCXAC_3P = "SET_TIMER_XUCXAC_3P";
export const SET_PHIEN_XUCXAC_3P = "SET_PHIEN_XUCXAC_3P";
export const SET_TINH_TRANG_XUCXAC_3P = "SET_TINH_TRANG_XUCXAC_3P";
export const SET_KET_QUA_PHIEN_TRUOC_XUCXAC_3P = "SET_KET_QUA_PHIEN_TRUOC_XUCXAC_3P";
export const SET_KET_QUA_XUCXAC_3P = "SET_KET_QUA_XUCXAC_3P";
export const SET_IS_PLAY_GAME_XUCXAC_3P = "SET_IS_PLAY_GAME_XUCXAC_3P";

// GAME XOCDIA 1P
export const SET_TIMER_XOCDIA_1P = "SET_TIMER_XOCDIA_1P";
export const SET_PHIEN_XOCDIA_1P = "SET_PHIEN_XOCDIA_1P";
export const SET_TINH_TRANG_XOCDIA_1P = "SET_TINH_TRANG_XOCDIA_1P";
export const SET_KET_QUA_PHIEN_TRUOC_XOCDIA_1P = "SET_KET_QUA_PHIEN_TRUOC_XOCDIA_1P";
export const SET_KET_QUA_XOCDIA_1P = "SET_KET_QUA_XOCDIA_1P";
export const SET_IS_PLAY_GAME_XOCDIA_1P = "SET_IS_PLAY_GAME_XOCDIA_1P";

// GAME XOSO 3P
export const SET_TIMER_XOSO_3P = "SET_TIMER_XOSO_3P";
export const SET_PHIEN_XOSO_3P = "SET_PHIEN_XOSO_3P";
export const SET_TINH_TRANG_XOSO_3P = "SET_TINH_TRANG_XOSO_3P";
export const SET_KET_QUA_PHIEN_TRUOC_XOSO_3P = "SET_KET_QUA_PHIEN_TRUOC_XOSO_3P";
export const SET_KET_QUA_XOSO_3P = "SET_KET_QUA_XOSO_3P";
export const SET_IS_PLAY_GAME_XOSO_3P = "SET_IS_PLAY_GAME_XOSO_3P";
// GAME XOSO 5P
export const SET_TIMER_XOSO_5P = "SET_TIMER_XOSO_5P";
export const SET_PHIEN_XOSO_5P = "SET_PHIEN_XOSO_5P";
export const SET_TINH_TRANG_XOSO_5P = "SET_TINH_TRANG_XOSO_5P";
export const SET_KET_QUA_PHIEN_TRUOC_XOSO_5P = "SET_KET_QUA_PHIEN_TRUOC_XOSO_5P";
export const SET_KET_QUA_XOSO_5P = "SET_KET_QUA_XOSO_5P";
export const SET_IS_PLAY_GAME_XOSO_5P = "SET_IS_PLAY_GAME_XOSO_5P";
